### ISSUE TITLE
Followup on tfjs-node error

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-ui#127]
Tensorflow's [tfjs-node version 4.2.0](https://www.npmjs.com/package/@tensorflow/tfjs-node) released on Jan 3, 2023 caused the scheduled GH actions that were generating Stampy's FAQ encodings to fail. We've reverted to version 4.1.0 to avoid the error but need to:
1. Create standalone code based on [`questions-encodings.mjs`](https://github.com/StampyAI/stampy-ui/blob/master/questions-encodings.mjs) to reproduce the error then use the [bug report template](https://github.com/tensorflow/tfjs/blob/master/.github/ISSUE_TEMPLATE/00-bug-issue.md) to file a [GitHub Issue tag type:bug](https://github.com/tensorflow/tfjs/issues) along with [failure log](https://github.com/StampyAI/stampy-ui/actions/runs/3867224986/jobs/6591862952)
2. Follow up when fixed then update [`gen-encodings-deploy.yml`](https://github.com/ccstan99/stampy-ui/blob/master/.github/workflows/gen-encodings-deploy.yml) to remove specification for version @4.1.0 when calling `npm install tfjs-node`

```
/home/runner/work/stampy-ui/stampy-ui/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:2978
    return env().platform.isTypedArray(a);
                          ^
TypeError: env(...).platform.isTypedArray is not a function
    at isTypedArray (/home/runner/work/stampy-ui/stampy-ui/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:2978:27)
    at inferShape (/home/runner/work/stampy-ui/stampy-ui/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5428:9)
    at tensor1d (/home/runner/work/stampy-ui/stampy-ui/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:18528:25)
    at /home/runner/work/stampy-ui/stampy-ui/node_modules/@tensorflow/tfjs-node/dist/kernels/StridedSlice.js:35:51
    at /home/runner/work/stampy-ui/stampy-ui/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4506:22
    at Engine.scopedRun (/home/runner/work/stampy-ui/stampy-ui/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4516:23)
    at Engine.tidy (/home/runner/work/stampy-ui/stampy-ui/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4505:21)
    at tidy (/home/runner/work/stampy-ui/stampy-ui/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8053:19)
    at Object.kernelFunc (/home/runner/work/stampy-ui/stampy-ui/node_modules/@tensorflow/tfjs-node/dist/kernels/StridedSlice.js:34:32)
    at kernelFunc (/home/runner/work/stampy-ui/stampy-ui/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4651:32)
Error: Process completed with exit code 1.
```

**Comment by ccstan99** [comment]
In my procrastination, tfjs-node apparently fixed this already. Looks like we're currently using version 4.6.0 in the stampy-nlp repo just fine.
